# action.yml
name: 'Docker Run Action'
description: 'Run a command in a new container'
inputs:
  docker_image:
    description: 'Docker Image to run'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
